server:
  port: 5050

jwt:
  signer-key: "B+jgFk5rkhAinZn4u41/0oWk9SKpPRCob+bkV7XKZKO0WSDlsrasiE9myU4MeicG"

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ASSIGNMENT_JAVA6;encrypt=false;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect



